from pathlib import Path

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[3]

PRIORITIZED_FILE = (
    PROJECT_ROOT
    / "data"
    / "prioritized_data"
    / "prioritized_maintenance.csv"
)

SHAP_FILE = (
    PROJECT_ROOT
    / "data"
    / "prioritized_data"
    / "priority_explanations.csv"
)


SHAP_FEATURES = [
    "priority_score",
    "severity_score",
    "duration_minutes",
    "days_to_due",
    "km",
    "is_cluster_candidate",
]


SHAP_LABELS = {
    "priority_score": "Maintenance priority",
    "severity_score": "Severity",
    "duration_minutes": "Maintenance duration",
    "days_to_due": "Days to due",
    "km": "Location",
    "is_cluster_candidate": "Cluster candidate",
}


def load_prioritized_maintenance() -> pd.DataFrame:
    if not PRIORITIZED_FILE.exists():
        raise FileNotFoundError(
            f"Prioritized maintenance file not found: {PRIORITIZED_FILE}"
        )

    df = pd.read_csv(PRIORITIZED_FILE)

    if df.empty:
        raise ValueError("Prioritized maintenance dataset is empty.")

    return df


def load_shap_explanations() -> pd.DataFrame:
    if not SHAP_FILE.exists():
        raise FileNotFoundError(
            f"SHAP explanation file not found: {SHAP_FILE}"
        )

    df = pd.read_csv(SHAP_FILE)

    if df.empty:
        raise ValueError("SHAP explanation dataset is empty.")

    return df


def load_maintenance_with_explanations() -> pd.DataFrame:
    maintenance_df = load_prioritized_maintenance()
    shap_df = load_shap_explanations()

    available_features = [
        feature
        for feature in SHAP_FEATURES
        if feature in shap_df.columns
    ]

    shap_columns = [
        "request_id",
        *available_features,
    ]

    shap_subset = shap_df[shap_columns].copy()

    # Rename SHAP columns before merging so it is impossible
    # to confuse raw maintenance values with SHAP contributions.
    shap_subset = shap_subset.rename(
        columns={
            feature: f"{feature}_shap"
            for feature in available_features
        }
    )

    merged = maintenance_df.merge(
        shap_subset,
        on="request_id",
        how="left",
    )

    return merged


def _clean_record(record: dict) -> dict:
    """
    Convert pandas/numpy values into JSON-safe Python values.
    """

    cleaned = {}

    for key, value in record.items():
        if pd.isna(value):
            cleaned[key] = None
        elif hasattr(value, "item"):
            cleaned[key] = value.item()
        else:
            cleaned[key] = value

    return cleaned


def _build_shap_explanation(record: dict) -> list[dict]:
    """
    Convert actual SHAP feature contributions into
    controller-friendly explanations.

    Positive SHAP value:
        pushes the model output higher.

    Negative SHAP value:
        pushes the model output lower.

    The contribution comes specifically from the
    *_shap fields generated by the SHAP pipeline.
    """

    explanations = []

    for feature in SHAP_FEATURES:
        shap_column = f"{feature}_shap"

        value = record.get(shap_column)

        if value is None:
            continue

        try:
            contribution = float(value)
        except (TypeError, ValueError):
            continue

        if contribution > 0:
            direction = "increases priority"
        elif contribution < 0:
            direction = "reduces priority"
        else:
            direction = "neutral"

        explanations.append(
            {
                "feature": feature,
                "label": SHAP_LABELS.get(
                    feature,
                    feature.replace("_", " ").title(),
                ),
                "contribution": round(contribution, 4),
                "direction": direction,
            }
        )

    explanations.sort(
        key=lambda item: abs(item["contribution"]),
        reverse=True,
    )

    return explanations


def _build_top_explanation(record: dict) -> str | None:
    explanations = _build_shap_explanation(record)

    if not explanations:
        return None

    top = explanations[0]

    if top["contribution"] > 0:
        return (
            f"{top['label']} is the strongest factor increasing "
            f"the model priority."
        )

    if top["contribution"] < 0:
        return (
            f"{top['label']} is the strongest factor reducing "
            f"the model priority."
        )

    return (
        f"{top['label']} has the strongest neutral contribution."
    )


def _prepare_record(record: dict) -> dict:
    cleaned = _clean_record(record)

    shap_explanation = _build_shap_explanation(cleaned)

    cleaned["shap_explanation"] = shap_explanation
    cleaned["top_priority_reason"] = _build_top_explanation(cleaned)

    # Remove raw SHAP columns from the top-level API response.
    # The structured shap_explanation array contains them instead.
    for feature in SHAP_FEATURES:
        cleaned.pop(f"{feature}_shap", None)

    return cleaned


def get_maintenance(
    limit: int = 100,
    department: str | None = None,
    section_code: str | None = None,
    status: str | None = None,
    search: str | None = None,
):
    df = load_maintenance_with_explanations()

    if department:
        df = df[
            df["department"].astype(str).str.upper()
            == department.upper()
        ]

    if section_code:
        df = df[
            df["mapped_section_code"].astype(str).str.upper()
            == section_code.upper()
        ]

    if status:
        df = df[
            df["status"].astype(str).str.lower()
            == status.lower()
        ]

    if search:
        search_value = search.strip().lower()

        searchable_columns = [
            "request_id",
            "department",
            "department_name",
            "defect_type",
            "required_resource",
            "mapped_section_code",
            "mapped_section_name",
            "status",
        ]

        mask = pd.Series(False, index=df.index)

        for column in searchable_columns:
            if column in df.columns:
                mask = mask | (
                    df[column]
                    .astype(str)
                    .str.lower()
                    .str.contains(
                        search_value,
                        regex=False,
                        na=False,
                    )
                )

        df = df[mask]

    df = df.sort_values(
        by=["ml_priority_score", "priority_rank"],
        ascending=[False, True],
    )

    records = df.head(limit).to_dict(orient="records")

    return [
        _prepare_record(record)
        for record in records
    ]


def get_maintenance_summary():
    df = load_prioritized_maintenance()

    department_distribution = (
        df["department"]
        .value_counts()
        .to_dict()
    )

    priority_distribution = (
        df["priority"]
        .value_counts()
        .to_dict()
    )

    status_distribution = (
        df["status"]
        .value_counts()
        .to_dict()
    )

    section_distribution = (
        df["mapped_section_code"]
        .value_counts()
        .to_dict()
    )

    return {
        "total_requests": int(len(df)),
        "average_ml_priority": round(
            float(df["ml_priority_score"].mean()),
            2,
        ),
        "highest_ml_priority": round(
            float(df["ml_priority_score"].max()),
            2,
        ),
        "cluster_candidates": int(
            df["is_cluster_candidate"].sum()
        ),
        "department_distribution": department_distribution,
        "priority_distribution": priority_distribution,
        "status_distribution": status_distribution,
        "section_distribution": section_distribution,
    }


def get_maintenance_request(request_id: str):
    df = load_maintenance_with_explanations()

    result = df[
        df["request_id"].astype(str).str.upper()
        == request_id.upper()
    ]

    if result.empty:
        return None

    record = result.iloc[0].to_dict()

    return _prepare_record(record)