from pathlib import Path

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[3]
OPPORTUNITY_FILE = PROJECT_ROOT / "data" / "opportunities" / "joint_opportunities.csv"


def load_opportunities() -> pd.DataFrame:
    """
    Load joint maintenance opportunities generated by
    intelligence.opportunities.detector.
    """

    if not OPPORTUNITY_FILE.exists():
        raise FileNotFoundError(
            f"Joint opportunity file not found: {OPPORTUNITY_FILE}"
        )

    df = pd.read_csv(OPPORTUNITY_FILE)

    return df


def get_opportunities(limit: int = 100) -> list[dict]:
    """
    Return joint maintenance opportunities for the API.

    The detector may generate thousands of candidates, so the API
    returns a configurable number of records rather than loading
    every record into the frontend at once.
    """

    df = load_opportunities()

    df = df.sort_values(
        by="opportunity_score",
        ascending=False,
    )

    records = df.head(limit).copy()

    records = records.where(
        pd.notna(records),
        None,
    )

    return records.to_dict(orient="records")


def get_opportunity_summary() -> dict:
    """
    Return summary statistics for the joint opportunity dataset.
    """

    df = load_opportunities()

    total = len(df)

    status_counts = (
        df["status"]
        .value_counts()
        .to_dict()
        if "status" in df.columns
        else {}
    )

    section_counts = (
        df["section_code"]
        .value_counts()
        .to_dict()
        if "section_code" in df.columns
        else {}
    )

    return {
        "total_opportunities": int(total),
        "status_distribution": {
            str(key): int(value)
            for key, value in status_counts.items()
        },
        "section_distribution": {
            str(key): int(value)
            for key, value in section_counts.items()
        },
        "average_opportunity_score": round(
            float(df["opportunity_score"].mean()),
            2,
        ),
        "highest_opportunity_score": round(
            float(df["opportunity_score"].max()),
            2,
        ),
    }